version: "3.7"
services:
  website:
    build: .
    image: cgc-website
    env_file: .env
    # environment:
    #   - CARAPI_KEY=xxx
    #   - EMAIL_HOST_PASSWORD_CGC=xxx
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    expose:
      - 8000

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /opt/certs:/etc/ssl
    ports:
      - "80:80"
      - "443:443"
