# Generated by Django 3.1.4 on 2021-01-29 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='client_name', max_length=50)),
                ('image', models.ImageField(upload_to='client_logos')),
            ],
        ),
        migrations.CreateModel(
            name='CommonText',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesItem',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(default='default.jpg', upload_to='team_avatars')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowItem',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowItemTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=100)),
                ('point01', models.CharField(max_length=200)),
                ('point02', models.CharField(blank=True, max_length=200)),
                ('point03', models.CharField(blank=True, max_length=200)),
                ('point04', models.CharField(blank=True, max_length=200)),
                ('point05', models.CharField(blank=True, max_length=200)),
                ('workf_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.workflowitem')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMemberTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=8)),
                ('role', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.teammember')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesItemTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=8)),
                ('headline', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.servicesitem')),
            ],
        ),
        migrations.CreateModel(
            name='CommonTextTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=8)),
                ('translation', models.TextField()),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.commontext')),
            ],
        ),
    ]
